org: sidd34po
app: elasticsearch
service: ElasticSearch
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  addDataToElastic:
    handler: index.addDataToElastic
    events:
      - http:
          path: /
          method: post
          cors: true
    environment:
      elasticURL:
        Fn::GetAtt: [ ElasticSearchInstance , DomainEndpoint ]
  
  getDataFromElastic:
    handler: index.getDataFromElastic
    events:
      - http:
          path: /
          method: get
          cors: true
    environment:
      elasticURL:
        Fn::GetAtt: [ ElasticSearchInstance , DomainEndpoint ]

resources:
  Resources:
    ElasticSearchInstance:
      Type: AWS::Elasticsearch::Domain
      Properties:
        EBSOptions:
          EBSEnabled: true
          VolumeType: gp2
          VolumeSize: 10
        ElasticsearchClusterConfig:
          InstanceType: t2.small.elasticsearch
          InstanceCount: 1
          DedicatedMasterEnabled: false
          ZoneAwarenessEnabled: false
        ElasticsearchVersion: "7.9"